apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
spec:
  selector:
    app: clickhouse
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
      nodePort: 30001
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30002
  type: NodePort
